### PR TITLE
restore timeout_ops whatever happened

### PR DESCRIPTION
**Pull request by erwinkinn**
# Description

The problem is when I set the special timeout for the operation and then handle ScrapliTimeout  (Why am I doing it? This why: https://github.com/carlmontanari/scrapli/issues/285 ;)) and proceed my script execution, I see that the timeout  remains actual for the second and all the rest of further commands. The reason is obvious.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Manually. 

# Checklist:

- [x] My code follows the style guidelines of this project (no GitHub actions complaints! run `make lint` before
 committing!)
- [x] I have commented my code, pydocstyle and darglint are happy, docstrings are in google docstring format, and all
 docstrings include a summary, args, returns and raises fields (even if N/A)
- [x] I have added tests that prove my fix is effective or that my feature works, if adding "functional" tests please
 note if there are any considerations for the vrnetlab setup
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by carlmontanari** [comment]
thanks for this @erwinkinn !

makes sense to me! I imagine this should also apply to the sync bits too right? would you mind adding that? and if you are feeling feisty and have the time -- perhaps a test? I think that'd be good so we dont regress here since I cant for sure imagine I will forget about all of this in like a week or so :D 

test could be pretty simple copy/pasta of [these](https://github.com/carlmontanari/scrapli/blob/d1e5e0a47dd08d73c44a2ebeb0616e475f032d43/tests/unit/test_decorators.py#L250-L287) I think -- raise a timeout and then make sure the timeout is set back nicely.

**Comment by erwinkinn** [comment]
Hi, @carlmontanari! Of course, no problem. I'll do this a bit later. I always forget about we have a synchronous version :) Also I have an interesting proposal about testing aids. In my project I use so called emulators that are founded on asyncssh and telnetlib3, so I need no third party servers for testing, I just run my test and emulators within the same event loop and interact with them. Unfortunately it won't work this blocking calls and so on (async only). Would it be useful to bring my elephant here?

**Comment by carlmontanari** [comment]
sounds great!

regarding mock ssh stuff. we actually already have that (or at least part way). [here](https://github.com/carlmontanari/scrapli/tree/main/tests/integration) the idea is to use [scrapli replay](https://github.com/scrapli/scrapli_replay) -- the least loved but probably coolest scrapli thing haha.

**Comment by erwinkinn** [comment]
Hello, @carlmontanari, we're here again with the pr :) Is is OK now?

**Comment by carlmontanari** [comment]
will check this out probably Saturday (but looks great at quick check) -- do we also need that other pr I opened? cc @rlad78 too

**Comment by carlmontanari** [comment]
lgtm, thanks a bunch @erwinkinn ! just pushed a changelog entry and will let build finish just for kicks then will get this merged. lemme know in the other pr if we still need that or what!

**Comment by erwinkinn** [comment]
Hi, Carl! Thank you for your responsiveness. It's always exciting to have a productive collaboration within the useful project ;) I think we need no more changes at the moment. Now, when the timeout_ops is kept saved, I can just handle that ScrapliTimeoutError and keep going with the closed connection and calling my "onclose" callbacks. Handling this on scrapli side would complicate the library. And as we know "Simple is better than complex".

**Pull request merged**
