### PR TITLE
Let mypy infer the correct context vars types

### PR DESCRIPTION
**Pull request by erwinkinn**
# Description

Hi there! Just a little problem related to mypy and type checking.
You use the reinterpret cast in `__new__` method (it's not quite good, but not an error though), hence in the next code the device object's type is inferred as `Scrapli`.
```
from scrapli import Scrapli
def test_():
    device = Scrapli(**{})
    device.open()
    device.send_command("?")
``` 
But in the next example the `device` type is inferred as a `Driver`, cause this is the ancestor where an  `__enter__` method is
declared in and the return value is annotated as `"Driver"`
```
from scrapli import Scraply
def test_():
    with Scraply(**{}) as device:
        device.send_command("?")
```
The problem is that neither `Driver` nor `BaseDriver` declares not `send_command` method, hence the above code breaks the rules.
Letting mypy do its job with no additional hints fixes it.

All the same is for the asynchronous versions of the drivers. 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Before:
image

After:
image

# Checklist:

- [x] My code follows the style guidelines of this project (no GitHub actions complaints! run `make lint` before
 committing!)
- [x] I have commented my code, pydocstyle and darglint are happy, docstrings are in google docstring format, and all
 docstrings include a summary, args, returns and raises fields (even if N/A)
- [x] I have added tests that prove my fix is effective or that my feature works, if adding "functional" tests please
 note if there are any considerations for the vrnetlab setup
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by carlmontanari** [comment]
Hey @erwinkinn 

Thanks for opening this. I see what you are saying from the screenshot, however I think this is a vscode issue not mypy. Pycharm correctly figures out device methods without any changes. Also, removing the return type will cause mypy to complain about not having any return type specified of course. 

Screen Shot 2022-06-18 at 9 34 56 AM

The Scrapli "factory" returns an instance of Scrapli (or AsyncScrapli in the async one of course), which the editor should be smart enough to see is in fact a NetworkDriver (or AsyncNetworkDriver) (because the "factory" class inherits from the respective network driver). So I don't think there is any issue with mypy or the typing here, and I'm inclined to leave things the way they are unless there is something im not understanding?

Carl

**Comment by erwinkinn** [comment]
> Hey @erwinkinn
> 
> Thanks for opening this. I see what you are saying from the screenshot, however I think this is a vscode issue not mypy. Pycharm correctly figures out device methods without any changes. Also, removing the return type will cause mypy to complain about not having any return type specified of course.
> 
> Screen Shot 2022-06-18 at 9 34 56 AM
> 
> The Scrapli "factory" returns an instance of Scrapli (or AsyncScrapli in the async one of course), which the editor should be smart enough to see is in fact a NetworkDriver (or AsyncNetworkDriver) (because the "factory" class inherits from the respective network driver). So I don't think there is any issue with mypy or the typing here, and I'm inclined to leave things the way they are unless there is something im not understanding?
> 
> Carl

Hello, Carl!
Thanks for answering ) It's an interesting case though. Looks like mypy doesn't track an obvious problem. 
Please consider the next case:
```
class B:
    def __enter__(self) -> "B":
        return self

    def __exit__(self, *_) -> None:
        ...

class D(B):
    def foo(self) -> int:
        ...

def bar(x: D):
    x.foo()

def main():
    with D() as d:
        bar(d)

main()
```
As far as the base class' method returns an instance of the base class (even if call it from the descendant), we will have a base class instance that has no `foo` method, hence we cannot pass such an object to the `bar` function. 
I think that mypy is just smart enough to infer the type of a returned instance correctly and may be this is the case when "practicality beats purity" and contexts are handled the special way. 
I think I should ask mypy devs about this. 
Thanks again ;)

**Comment by erwinkinn** [comment]
@carlmontanari, guys from [gitter.im](https://gitter.im/python/typing?at=62b00c3a8fe56a38b5a4fb68) have helped me understand this. Consider the code below.
image
Mypy start claiming this as a bug right after I have added a return type to my main function.
Also it detects an error when it's run in the `strict` mode. This like:
image
So this is definitely not a VSCode problem. This is the Liskov rule which is broken here.

**Comment by carlmontanari** [comment]
@erwinkinn sorry I've been busy and haven't gotten back to this. So what is the final setup that will appease mypy?

**Comment by erwinkinn** [comment]
@carlmontanari, thanks for returning to this ) 
I just wanna say that obviously you want your `__enter__` method to return an instance of the class the method was called for. So you have to just let *mypy* to infer a type rather than defining it manually (this is what my PR actually does). 
_class Driver_ has no `send_command` method, but this is the place where the `__enter__` method is defined. This context method is inherited in _GenericDriver_ and this last guy does have `send_command` method. Finally when I so smth like
`with GenericDriver() as driver: ...`, I expect the driver to be of type _GenericDriver_ rather than just _Driver_. But, I have _Driver_, cause this is the declared type for the context to return.
Please consider [this example](https://github.com/carlmontanari/scrapli/pull/243#issuecomment-1160404875). This is exactly the same what happens in scrapli's code, isn't it?

**Comment by carlmontanari** [comment]
Ok I get what you are saying and am good with it (thanks for bearing with me!) -- one thing remains though: what do we do to tell mypy to not complain about this? I feel like just a `type: ignore` is probably not the "right" thing to do here, but of course mypy is complaining about no return information as it sits now. Is there a "nice" way to signify to mypy that it should just infer things here and not complain about lack of return information?

**Comment by erwinkinn** [comment]
@carlmontanari, pardon me for such a long delay, I'm so crazy busy at my work... Yes, I understand your question. Actually if mypy isn't run in this `--strict` mode, it must not to report an absence of the return information for you `__aenter__` method. Another option is to use a Generic Type for the method if you wanna keep a return value. Let me add just yet another commit...

**Comment by erwinkinn** [comment]
I've added a Generic type. Now we have both -- the type defined and a normal behaviour for the descendants. 

Oh, BTW, I have found just yet another problem I want to ask about. When I enter an "exit" command, the remote server terminates a session (it must do so though). Right now scrapli doesn't handle this situation. It eagers to read until a prompt is received, getting an empty byte string again and again from the underlaying transport.
Is handling such a leave-the-session command as "exit" a use case for scrapli? I could make a PR if so.

**Comment by carlmontanari** [comment]
hey @erwinkinn 

It looks like [mypy is still upset](https://github.com/carlmontanari/scrapli/runs/7431614068?check_suite_focus=true#step:7:782), now about the new typevar not having an open method, though I imagine it would complain about the next method too if that object for some reason had an open method. 

> When I enter an "exit" command, the remote server terminates a session (it must do so though). Right now scrapli doesn't handle this situation.

In most (all?) cases, if you are using a "network" platform, this should be handled for you in the "on_close" function. Those functions just do something like: `conn.channel.write("exit")` -- if you don't have a platform/are doing custom stuff you could just exit like that.

**Comment by erwinkinn** [comment]
Oh, I'm sorry. Of course this typevar must be bound to the type it refers to. One more commit follows.

About "exit" functionality. Well, OK. I thought that. Actually I'm trying to use scrapli not as a network engineer to automate some boring stuff, but for my testing framework. That's why this special case is not an option for me.  I mean I understand that normally one has to just close the connection or leave the connection context in order to exit a session, but I'm trying to make a Device abstraction that must handle both of the `device.console.run("exit")` and the `device.console.run("ls -l")` all the same way. It looks like I have to make a workaround, cause leaving a session this way is not the case for scrapli.

**Comment by erwinkinn** [comment]
Ok, here's the commit. It looks like everything is ok for now.
<details>
<summary>This is what mypy-0.971 (newer than yours) says.  I see no the subject related errors</summary>
<pre>
>mypy --strict scrapli
scrapli\helper.py:10: error: Library stubs not installed for "pkg_resources" (or incompatible with Python 3.10)
    import pkg_resources  # pylint: disable=C0411
    ^
scrapli\helper.py:10: note: Hint: "python3 -m pip install types-setuptools"
scrapli\transport\plugins\paramiko\transport.py:5: error: Library stubs not installed for "paramiko" (or incompatible with Python 3.10)
    from paramiko import Channel
    ^
scrapli\transport\plugins\paramiko\transport.py:5: note: Hint: "python3 -m pip install types-paramiko"
scrapli\transport\plugins\paramiko\transport.py:5: note: (or run "mypy --install-types" to install all missing stub packages)
scrapli\transport\plugins\paramiko\transport.py:5: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
scrapli\transport\plugins\paramiko\transport.py:7: error: Library stubs not installed for "paramiko.rsakey" (or incompatible with Python 3.10)
    from paramiko.rsakey import RSAKey
    ^
scrapli\transport\plugins\paramiko\transport.py:8: error: Library stubs not installed for "paramiko.ssh_exception" (or incompatible with Python 3.10)
    from paramiko.ssh_exception import AuthenticationException
    ^
scrapli\transport\plugins\paramiko\transport.py:80: error: Unused "type: ignore" comment
                self.session = _ParamikoTransport(self.socket.sock)  # type: ignore
                ^
scrapli\decorators.py:105: error: Module has no attribute "SIGALRM"
                    old = signal.signal(signal.SIGALRM, self._signal_raise_exception)
                                        ^
scrapli\decorators.py:106: error: Module has no attribute "setitimer"
                    signal.setitimer(signal.ITIMER_REAL, self.transport_timeout_transport)
                    ^
scrapli\decorators.py:106: error: Module has no attribute "ITIMER_REAL"
                    signal.setitimer(signal.ITIMER_REAL, self.transport_timeout_transport)
                                     ^
scrapli\decorators.py:111: error: Module has no attribute "setitimer"
                            signal.setitimer(signal.ITIMER_REAL, 0)
                            ^
scrapli\decorators.py:111: error: Module has no attribute "ITIMER_REAL"
                            signal.setitimer(signal.ITIMER_REAL, 0)
                                             ^
scrapli\decorators.py:112: error: Module has no attribute "SIGALRM"
                            signal.signal(signal.SIGALRM, old)
                                          ^
scrapli\decorators.py:286: error: Module has no attribute "SIGALRM"
                    old = signal.signal(signal.SIGALRM, self._signal_raise_exception)
                                        ^
scrapli\decorators.py:287: error: Module has no attribute "setitimer"
                    signal.setitimer(signal.ITIMER_REAL, self.channel_timeout_ops)
                    ^
scrapli\decorators.py:287: error: Module has no attribute "ITIMER_REAL"
                    signal.setitimer(signal.ITIMER_REAL, self.channel_timeout_ops)
                                     ^
scrapli\decorators.py:292: error: Module has no attribute "setitimer"
                            signal.setitimer(signal.ITIMER_REAL, 0)
                            ^
scrapli\decorators.py:292: error: Module has no attribute "ITIMER_REAL"
                            signal.setitimer(signal.ITIMER_REAL, 0)
                                             ^
scrapli\decorators.py:293: error: Module has no attribute "SIGALRM"
                            signal.signal(signal.SIGALRM, old)
                                          ^
Found 17 errors in 3 files (checked 67 source files)
</pre>
</details>

**Comment by carlmontanari** [comment]
> It looks like I have to make a workaround, cause leaving a session this way is not the case for scrapli

Yeah I think probably I'd say that is outside of scrapli "normal" scope -- I think/hope you should have all the tools available within scrapli to make that happen, but as you say would have to roll your own.

Thanks for sticking with me on this one! LGTM, will merge this and try to sort some of the ci issues (I'm still unclear why the Darwin builds are just never completing... haven't had time to look at it yet!)

**Pull request merged**
