### PR TITLE
_post_init()

### PR DESCRIPTION
**Pull request by KlimchevKonstantin**
In continuation https://github.com/carlmontanari/scrapli/discussions/281

Adding the _post_init method to the base class. This method could be called after the init method of the underlying sync/async drivers.

Needed for e.g. redefinition
```
conn.channel._auth_telnet_login_pattern
```
PS
Unfortunately, my knowledge is not enough to formalize the code correctly.
Only denote

### CODE REVIEW

**Comment by carlmontanari** [comment]
👋 hey there! thanks for getting this rolling. I just pushed a commit to this that I think should do what we are looking for. would you mind testing this out and seeing if this works for what we were talking about in the discussion!?

**Comment by KlimchevKonstantin** [comment]
Carl,

Everything works.  
super :-)

Thank you

**Comment by carlmontanari** [comment]
hah, don't close it we gotta merge it now :D thanks for the help on this one!

**Comment by KlimchevKonstantin** [comment]
ouch.... I apologize. I'll fix it :-)


P.S. I have one more question... soon... :-)

**Comment by carlmontanari** [comment]
hah no worries! its all sorted -- reopened and then merged!

**Pull request merged**
